/**
 * ISO 3166-1 country codes.
 *
 * Alpha-2, alpha-3 and numeric codes follow ISO 3166-1.
 * English names are sourced from the installed ISO dataset (pycountry).
 * Vietnamese display names are sourced from Unicode CLDR (Babel).
 *
 * Passport note: most MRZ country codes are ISO alpha-3, but ICAO also
 * defines a small number of non-ISO codes. Keep those in a separate map.
 */

export interface Country {
  readonly alpha2: string;
  readonly alpha3: string;
  /** Kept as string to preserve leading zeroes. */
  readonly numeric: string;
  readonly name: string;
  readonly nameVi: string;
  readonly officialName?: string;
  readonly commonName?: string;
}

export const COUNTRIES = [
  {
    alpha2: "AD",
    alpha3: "AND",
    numeric: "020",
    name: "Andorra",
    nameVi: "Andorra",
    officialName: "Principality of Andorra",
  },
  {
    alpha2: "AE",
    alpha3: "ARE",
    numeric: "784",
    name: "United Arab Emirates",
    nameVi: "Các Tiểu Vương quốc Ả Rập Thống nhất",
  },
  {
    alpha2: "AF",
    alpha3: "AFG",
    numeric: "004",
    name: "Afghanistan",
    nameVi: "Afghanistan",
    officialName: "Islamic Republic of Afghanistan",
  },
  {
    alpha2: "AG",
    alpha3: "ATG",
    numeric: "028",
    name: "Antigua and Barbuda",
    nameVi: "Antigua và Barbuda",
  },
  {
    alpha2: "AI",
    alpha3: "AIA",
    numeric: "660",
    name: "Anguilla",
    nameVi: "Anguilla",
  },
  {
    alpha2: "AL",
    alpha3: "ALB",
    numeric: "008",
    name: "Albania",
    nameVi: "Albania",
    officialName: "Republic of Albania",
  },
  {
    alpha2: "AM",
    alpha3: "ARM",
    numeric: "051",
    name: "Armenia",
    nameVi: "Armenia",
    officialName: "Republic of Armenia",
  },
  {
    alpha2: "AO",
    alpha3: "AGO",
    numeric: "024",
    name: "Angola",
    nameVi: "Angola",
    officialName: "Republic of Angola",
  },
  {
    alpha2: "AQ",
    alpha3: "ATA",
    numeric: "010",
    name: "Antarctica",
    nameVi: "Nam Cực",
  },
  {
    alpha2: "AR",
    alpha3: "ARG",
    numeric: "032",
    name: "Argentina",
    nameVi: "Argentina",
    officialName: "Argentine Republic",
  },
  {
    alpha2: "AS",
    alpha3: "ASM",
    numeric: "016",
    name: "American Samoa",
    nameVi: "Samoa thuộc Mỹ",
  },
  {
    alpha2: "AT",
    alpha3: "AUT",
    numeric: "040",
    name: "Austria",
    nameVi: "Áo",
    officialName: "Republic of Austria",
  },
  {
    alpha2: "AU",
    alpha3: "AUS",
    numeric: "036",
    name: "Australia",
    nameVi: "Australia",
  },
  {
    alpha2: "AW",
    alpha3: "ABW",
    numeric: "533",
    name: "Aruba",
    nameVi: "Aruba",
  },
  {
    alpha2: "AX",
    alpha3: "ALA",
    numeric: "248",
    name: "Åland Islands",
    nameVi: "Quần đảo Åland",
  },
  {
    alpha2: "AZ",
    alpha3: "AZE",
    numeric: "031",
    name: "Azerbaijan",
    nameVi: "Azerbaijan",
    officialName: "Republic of Azerbaijan",
  },
  {
    alpha2: "BA",
    alpha3: "BIH",
    numeric: "070",
    name: "Bosnia and Herzegovina",
    nameVi: "Bosnia và Herzegovina",
    officialName: "Republic of Bosnia and Herzegovina",
  },
  {
    alpha2: "BB",
    alpha3: "BRB",
    numeric: "052",
    name: "Barbados",
    nameVi: "Barbados",
  },
  {
    alpha2: "BD",
    alpha3: "BGD",
    numeric: "050",
    name: "Bangladesh",
    nameVi: "Bangladesh",
    officialName: "People's Republic of Bangladesh",
  },
  {
    alpha2: "BE",
    alpha3: "BEL",
    numeric: "056",
    name: "Belgium",
    nameVi: "Bỉ",
    officialName: "Kingdom of Belgium",
  },
  {
    alpha2: "BF",
    alpha3: "BFA",
    numeric: "854",
    name: "Burkina Faso",
    nameVi: "Burkina Faso",
  },
  {
    alpha2: "BG",
    alpha3: "BGR",
    numeric: "100",
    name: "Bulgaria",
    nameVi: "Bulgaria",
    officialName: "Republic of Bulgaria",
  },
  {
    alpha2: "BH",
    alpha3: "BHR",
    numeric: "048",
    name: "Bahrain",
    nameVi: "Bahrain",
    officialName: "Kingdom of Bahrain",
  },
  {
    alpha2: "BI",
    alpha3: "BDI",
    numeric: "108",
    name: "Burundi",
    nameVi: "Burundi",
    officialName: "Republic of Burundi",
  },
  {
    alpha2: "BJ",
    alpha3: "BEN",
    numeric: "204",
    name: "Benin",
    nameVi: "Benin",
    officialName: "Republic of Benin",
  },
  {
    alpha2: "BL",
    alpha3: "BLM",
    numeric: "652",
    name: "Saint Barthélemy",
    nameVi: "St. Barthélemy",
  },
  {
    alpha2: "BM",
    alpha3: "BMU",
    numeric: "060",
    name: "Bermuda",
    nameVi: "Bermuda",
  },
  {
    alpha2: "BN",
    alpha3: "BRN",
    numeric: "096",
    name: "Brunei Darussalam",
    nameVi: "Brunei",
  },
  {
    alpha2: "BO",
    alpha3: "BOL",
    numeric: "068",
    name: "Bolivia, Plurinational State of",
    nameVi: "Bolivia",
    officialName: "Plurinational State of Bolivia",
    commonName: "Bolivia",
  },
  {
    alpha2: "BQ",
    alpha3: "BES",
    numeric: "535",
    name: "Bonaire, Sint Eustatius and Saba",
    nameVi: "Ca-ri-bê Hà Lan",
    officialName: "Bonaire, Sint Eustatius and Saba",
  },
  {
    alpha2: "BR",
    alpha3: "BRA",
    numeric: "076",
    name: "Brazil",
    nameVi: "Brazil",
    officialName: "Federative Republic of Brazil",
  },
  {
    alpha2: "BS",
    alpha3: "BHS",
    numeric: "044",
    name: "Bahamas",
    nameVi: "Bahamas",
    officialName: "Commonwealth of the Bahamas",
  },
  {
    alpha2: "BT",
    alpha3: "BTN",
    numeric: "064",
    name: "Bhutan",
    nameVi: "Bhutan",
    officialName: "Kingdom of Bhutan",
  },
  {
    alpha2: "BV",
    alpha3: "BVT",
    numeric: "074",
    name: "Bouvet Island",
    nameVi: "Đảo Bouvet",
  },
  {
    alpha2: "BW",
    alpha3: "BWA",
    numeric: "072",
    name: "Botswana",
    nameVi: "Botswana",
    officialName: "Republic of Botswana",
  },
  {
    alpha2: "BY",
    alpha3: "BLR",
    numeric: "112",
    name: "Belarus",
    nameVi: "Belarus",
    officialName: "Republic of Belarus",
  },
  {
    alpha2: "BZ",
    alpha3: "BLZ",
    numeric: "084",
    name: "Belize",
    nameVi: "Belize",
  },
  {
    alpha2: "CA",
    alpha3: "CAN",
    numeric: "124",
    name: "Canada",
    nameVi: "Canada",
  },
  {
    alpha2: "CC",
    alpha3: "CCK",
    numeric: "166",
    name: "Cocos (Keeling) Islands",
    nameVi: "Quần đảo Cocos (Keeling)",
  },
  {
    alpha2: "CD",
    alpha3: "COD",
    numeric: "180",
    name: "Congo, The Democratic Republic of the",
    nameVi: "Congo - Kinshasa",
  },
  {
    alpha2: "CF",
    alpha3: "CAF",
    numeric: "140",
    name: "Central African Republic",
    nameVi: "Cộng hòa Trung Phi",
  },
  {
    alpha2: "CG",
    alpha3: "COG",
    numeric: "178",
    name: "Congo",
    nameVi: "Congo - Brazzaville",
    officialName: "Republic of the Congo",
  },
  {
    alpha2: "CH",
    alpha3: "CHE",
    numeric: "756",
    name: "Switzerland",
    nameVi: "Thụy Sĩ",
    officialName: "Swiss Confederation",
  },
  {
    alpha2: "CI",
    alpha3: "CIV",
    numeric: "384",
    name: "Côte d'Ivoire",
    nameVi: "Côte d’Ivoire",
    officialName: "Republic of Côte d'Ivoire",
  },
  {
    alpha2: "CK",
    alpha3: "COK",
    numeric: "184",
    name: "Cook Islands",
    nameVi: "Quần đảo Cook",
  },
  {
    alpha2: "CL",
    alpha3: "CHL",
    numeric: "152",
    name: "Chile",
    nameVi: "Chile",
    officialName: "Republic of Chile",
  },
  {
    alpha2: "CM",
    alpha3: "CMR",
    numeric: "120",
    name: "Cameroon",
    nameVi: "Cameroon",
    officialName: "Republic of Cameroon",
  },
  {
    alpha2: "CN",
    alpha3: "CHN",
    numeric: "156",
    name: "China",
    nameVi: "Trung Quốc",
    officialName: "People's Republic of China",
  },
  {
    alpha2: "CO",
    alpha3: "COL",
    numeric: "170",
    name: "Colombia",
    nameVi: "Colombia",
    officialName: "Republic of Colombia",
  },
  {
    alpha2: "CR",
    alpha3: "CRI",
    numeric: "188",
    name: "Costa Rica",
    nameVi: "Costa Rica",
    officialName: "Republic of Costa Rica",
  },
  {
    alpha2: "CU",
    alpha3: "CUB",
    numeric: "192",
    name: "Cuba",
    nameVi: "Cuba",
    officialName: "Republic of Cuba",
  },
  {
    alpha2: "CV",
    alpha3: "CPV",
    numeric: "132",
    name: "Cabo Verde",
    nameVi: "Cape Verde",
    officialName: "Republic of Cabo Verde",
  },
  {
    alpha2: "CW",
    alpha3: "CUW",
    numeric: "531",
    name: "Curaçao",
    nameVi: "Curaçao",
    officialName: "Curaçao",
  },
  {
    alpha2: "CX",
    alpha3: "CXR",
    numeric: "162",
    name: "Christmas Island",
    nameVi: "Đảo Giáng Sinh",
  },
  {
    alpha2: "CY",
    alpha3: "CYP",
    numeric: "196",
    name: "Cyprus",
    nameVi: "Síp",
    officialName: "Republic of Cyprus",
  },
  {
    alpha2: "CZ",
    alpha3: "CZE",
    numeric: "203",
    name: "Czechia",
    nameVi: "Séc",
    officialName: "Czech Republic",
  },
  {
    alpha2: "DE",
    alpha3: "DEU",
    numeric: "276",
    name: "Germany",
    nameVi: "Đức",
    officialName: "Federal Republic of Germany",
  },
  {
    alpha2: "DJ",
    alpha3: "DJI",
    numeric: "262",
    name: "Djibouti",
    nameVi: "Djibouti",
    officialName: "Republic of Djibouti",
  },
  {
    alpha2: "DK",
    alpha3: "DNK",
    numeric: "208",
    name: "Denmark",
    nameVi: "Đan Mạch",
    officialName: "Kingdom of Denmark",
  },
  {
    alpha2: "DM",
    alpha3: "DMA",
    numeric: "212",
    name: "Dominica",
    nameVi: "Dominica",
    officialName: "Commonwealth of Dominica",
  },
  {
    alpha2: "DO",
    alpha3: "DOM",
    numeric: "214",
    name: "Dominican Republic",
    nameVi: "Cộng hòa Dominica",
  },
  {
    alpha2: "DZ",
    alpha3: "DZA",
    numeric: "012",
    name: "Algeria",
    nameVi: "Algeria",
    officialName: "People's Democratic Republic of Algeria",
  },
  {
    alpha2: "EC",
    alpha3: "ECU",
    numeric: "218",
    name: "Ecuador",
    nameVi: "Ecuador",
    officialName: "Republic of Ecuador",
  },
  {
    alpha2: "EE",
    alpha3: "EST",
    numeric: "233",
    name: "Estonia",
    nameVi: "Estonia",
    officialName: "Republic of Estonia",
  },
  {
    alpha2: "EG",
    alpha3: "EGY",
    numeric: "818",
    name: "Egypt",
    nameVi: "Ai Cập",
    officialName: "Arab Republic of Egypt",
  },
  {
    alpha2: "EH",
    alpha3: "ESH",
    numeric: "732",
    name: "Western Sahara",
    nameVi: "Tây Sahara",
  },
  {
    alpha2: "ER",
    alpha3: "ERI",
    numeric: "232",
    name: "Eritrea",
    nameVi: "Eritrea",
    officialName: "the State of Eritrea",
  },
  {
    alpha2: "ES",
    alpha3: "ESP",
    numeric: "724",
    name: "Spain",
    nameVi: "Tây Ban Nha",
    officialName: "Kingdom of Spain",
  },
  {
    alpha2: "ET",
    alpha3: "ETH",
    numeric: "231",
    name: "Ethiopia",
    nameVi: "Ethiopia",
    officialName: "Federal Democratic Republic of Ethiopia",
  },
  {
    alpha2: "FI",
    alpha3: "FIN",
    numeric: "246",
    name: "Finland",
    nameVi: "Phần Lan",
    officialName: "Republic of Finland",
  },
  {
    alpha2: "FJ",
    alpha3: "FJI",
    numeric: "242",
    name: "Fiji",
    nameVi: "Fiji",
    officialName: "Republic of Fiji",
  },
  {
    alpha2: "FK",
    alpha3: "FLK",
    numeric: "238",
    name: "Falkland Islands (Malvinas)",
    nameVi: "Quần đảo Falkland",
  },
  {
    alpha2: "FM",
    alpha3: "FSM",
    numeric: "583",
    name: "Micronesia, Federated States of",
    nameVi: "Micronesia",
    officialName: "Federated States of Micronesia",
  },
  {
    alpha2: "FO",
    alpha3: "FRO",
    numeric: "234",
    name: "Faroe Islands",
    nameVi: "Quần đảo Faroe",
  },
  {
    alpha2: "FR",
    alpha3: "FRA",
    numeric: "250",
    name: "France",
    nameVi: "Pháp",
    officialName: "French Republic",
  },
  {
    alpha2: "GA",
    alpha3: "GAB",
    numeric: "266",
    name: "Gabon",
    nameVi: "Gabon",
    officialName: "Gabonese Republic",
  },
  {
    alpha2: "GB",
    alpha3: "GBR",
    numeric: "826",
    name: "United Kingdom",
    nameVi: "Vương quốc Anh",
    officialName: "United Kingdom of Great Britain and Northern Ireland",
  },
  {
    alpha2: "GD",
    alpha3: "GRD",
    numeric: "308",
    name: "Grenada",
    nameVi: "Grenada",
  },
  {
    alpha2: "GE",
    alpha3: "GEO",
    numeric: "268",
    name: "Georgia",
    nameVi: "Georgia",
  },
  {
    alpha2: "GF",
    alpha3: "GUF",
    numeric: "254",
    name: "French Guiana",
    nameVi: "Guiana thuộc Pháp",
  },
  {
    alpha2: "GG",
    alpha3: "GGY",
    numeric: "831",
    name: "Guernsey",
    nameVi: "Guernsey",
  },
  {
    alpha2: "GH",
    alpha3: "GHA",
    numeric: "288",
    name: "Ghana",
    nameVi: "Ghana",
    officialName: "Republic of Ghana",
  },
  {
    alpha2: "GI",
    alpha3: "GIB",
    numeric: "292",
    name: "Gibraltar",
    nameVi: "Gibraltar",
  },
  {
    alpha2: "GL",
    alpha3: "GRL",
    numeric: "304",
    name: "Greenland",
    nameVi: "Greenland",
  },
  {
    alpha2: "GM",
    alpha3: "GMB",
    numeric: "270",
    name: "Gambia",
    nameVi: "Gambia",
    officialName: "Republic of the Gambia",
  },
  {
    alpha2: "GN",
    alpha3: "GIN",
    numeric: "324",
    name: "Guinea",
    nameVi: "Guinea",
    officialName: "Republic of Guinea",
  },
  {
    alpha2: "GP",
    alpha3: "GLP",
    numeric: "312",
    name: "Guadeloupe",
    nameVi: "Guadeloupe",
  },
  {
    alpha2: "GQ",
    alpha3: "GNQ",
    numeric: "226",
    name: "Equatorial Guinea",
    nameVi: "Guinea Xích Đạo",
    officialName: "Republic of Equatorial Guinea",
  },
  {
    alpha2: "GR",
    alpha3: "GRC",
    numeric: "300",
    name: "Greece",
    nameVi: "Hy Lạp",
    officialName: "Hellenic Republic",
  },
  {
    alpha2: "GS",
    alpha3: "SGS",
    numeric: "239",
    name: "South Georgia and the South Sandwich Islands",
    nameVi: "Nam Georgia & Quần đảo Nam Sandwich",
  },
  {
    alpha2: "GT",
    alpha3: "GTM",
    numeric: "320",
    name: "Guatemala",
    nameVi: "Guatemala",
    officialName: "Republic of Guatemala",
  },
  { alpha2: "GU", alpha3: "GUM", numeric: "316", name: "Guam", nameVi: "Guam" },
  {
    alpha2: "GW",
    alpha3: "GNB",
    numeric: "624",
    name: "Guinea-Bissau",
    nameVi: "Guinea-Bissau",
    officialName: "Republic of Guinea-Bissau",
  },
  {
    alpha2: "GY",
    alpha3: "GUY",
    numeric: "328",
    name: "Guyana",
    nameVi: "Guyana",
    officialName: "Republic of Guyana",
  },
  {
    alpha2: "HK",
    alpha3: "HKG",
    numeric: "344",
    name: "Hong Kong",
    nameVi: "Đặc khu Hành chính Hồng Kông, Trung Quốc",
    officialName: "Hong Kong Special Administrative Region of China",
  },
  {
    alpha2: "HM",
    alpha3: "HMD",
    numeric: "334",
    name: "Heard Island and McDonald Islands",
    nameVi: "Quần đảo Heard và McDonald",
  },
  {
    alpha2: "HN",
    alpha3: "HND",
    numeric: "340",
    name: "Honduras",
    nameVi: "Honduras",
    officialName: "Republic of Honduras",
  },
  {
    alpha2: "HR",
    alpha3: "HRV",
    numeric: "191",
    name: "Croatia",
    nameVi: "Croatia",
    officialName: "Republic of Croatia",
  },
  {
    alpha2: "HT",
    alpha3: "HTI",
    numeric: "332",
    name: "Haiti",
    nameVi: "Haiti",
    officialName: "Republic of Haiti",
  },
  {
    alpha2: "HU",
    alpha3: "HUN",
    numeric: "348",
    name: "Hungary",
    nameVi: "Hungary",
    officialName: "Hungary",
  },
  {
    alpha2: "ID",
    alpha3: "IDN",
    numeric: "360",
    name: "Indonesia",
    nameVi: "Indonesia",
    officialName: "Republic of Indonesia",
  },
  {
    alpha2: "IE",
    alpha3: "IRL",
    numeric: "372",
    name: "Ireland",
    nameVi: "Ireland",
  },
  {
    alpha2: "IL",
    alpha3: "ISR",
    numeric: "376",
    name: "Israel",
    nameVi: "Israel",
    officialName: "State of Israel",
  },
  {
    alpha2: "IM",
    alpha3: "IMN",
    numeric: "833",
    name: "Isle of Man",
    nameVi: "Đảo Man",
  },
  {
    alpha2: "IN",
    alpha3: "IND",
    numeric: "356",
    name: "India",
    nameVi: "Ấn Độ",
    officialName: "Republic of India",
  },
  {
    alpha2: "IO",
    alpha3: "IOT",
    numeric: "086",
    name: "British Indian Ocean Territory",
    nameVi: "Lãnh thổ Ấn Độ Dương thuộc Anh",
  },
  {
    alpha2: "IQ",
    alpha3: "IRQ",
    numeric: "368",
    name: "Iraq",
    nameVi: "Iraq",
    officialName: "Republic of Iraq",
  },
  {
    alpha2: "IR",
    alpha3: "IRN",
    numeric: "364",
    name: "Iran, Islamic Republic of",
    nameVi: "Iran",
    officialName: "Islamic Republic of Iran",
    commonName: "Iran",
  },
  {
    alpha2: "IS",
    alpha3: "ISL",
    numeric: "352",
    name: "Iceland",
    nameVi: "Iceland",
    officialName: "Republic of Iceland",
  },
  {
    alpha2: "IT",
    alpha3: "ITA",
    numeric: "380",
    name: "Italy",
    nameVi: "Italy",
    officialName: "Italian Republic",
  },
  {
    alpha2: "JE",
    alpha3: "JEY",
    numeric: "832",
    name: "Jersey",
    nameVi: "Jersey",
  },
  {
    alpha2: "JM",
    alpha3: "JAM",
    numeric: "388",
    name: "Jamaica",
    nameVi: "Jamaica",
  },
  {
    alpha2: "JO",
    alpha3: "JOR",
    numeric: "400",
    name: "Jordan",
    nameVi: "Jordan",
    officialName: "Hashemite Kingdom of Jordan",
  },
  {
    alpha2: "JP",
    alpha3: "JPN",
    numeric: "392",
    name: "Japan",
    nameVi: "Nhật Bản",
  },
  {
    alpha2: "KE",
    alpha3: "KEN",
    numeric: "404",
    name: "Kenya",
    nameVi: "Kenya",
    officialName: "Republic of Kenya",
  },
  {
    alpha2: "KG",
    alpha3: "KGZ",
    numeric: "417",
    name: "Kyrgyzstan",
    nameVi: "Kyrgyzstan",
    officialName: "Kyrgyz Republic",
  },
  {
    alpha2: "KH",
    alpha3: "KHM",
    numeric: "116",
    name: "Cambodia",
    nameVi: "Campuchia",
    officialName: "Kingdom of Cambodia",
  },
  {
    alpha2: "KI",
    alpha3: "KIR",
    numeric: "296",
    name: "Kiribati",
    nameVi: "Kiribati",
    officialName: "Republic of Kiribati",
  },
  {
    alpha2: "KM",
    alpha3: "COM",
    numeric: "174",
    name: "Comoros",
    nameVi: "Comoros",
    officialName: "Union of the Comoros",
  },
  {
    alpha2: "KN",
    alpha3: "KNA",
    numeric: "659",
    name: "Saint Kitts and Nevis",
    nameVi: "St. Kitts và Nevis",
  },
  {
    alpha2: "KP",
    alpha3: "PRK",
    numeric: "408",
    name: "Korea, Democratic People's Republic of",
    nameVi: "Triều Tiên",
    officialName: "Democratic People's Republic of Korea",
    commonName: "North Korea",
  },
  {
    alpha2: "KR",
    alpha3: "KOR",
    numeric: "410",
    name: "Korea, Republic of",
    nameVi: "Hàn Quốc",
    commonName: "South Korea",
  },
  {
    alpha2: "KW",
    alpha3: "KWT",
    numeric: "414",
    name: "Kuwait",
    nameVi: "Kuwait",
    officialName: "State of Kuwait",
  },
  {
    alpha2: "KY",
    alpha3: "CYM",
    numeric: "136",
    name: "Cayman Islands",
    nameVi: "Quần đảo Cayman",
  },
  {
    alpha2: "KZ",
    alpha3: "KAZ",
    numeric: "398",
    name: "Kazakhstan",
    nameVi: "Kazakhstan",
    officialName: "Republic of Kazakhstan",
  },
  {
    alpha2: "LA",
    alpha3: "LAO",
    numeric: "418",
    name: "Lao People's Democratic Republic",
    nameVi: "Lào",
    commonName: "Laos",
  },
  {
    alpha2: "LB",
    alpha3: "LBN",
    numeric: "422",
    name: "Lebanon",
    nameVi: "Li-băng",
    officialName: "Lebanese Republic",
  },
  {
    alpha2: "LC",
    alpha3: "LCA",
    numeric: "662",
    name: "Saint Lucia",
    nameVi: "St. Lucia",
  },
  {
    alpha2: "LI",
    alpha3: "LIE",
    numeric: "438",
    name: "Liechtenstein",
    nameVi: "Liechtenstein",
    officialName: "Principality of Liechtenstein",
  },
  {
    alpha2: "LK",
    alpha3: "LKA",
    numeric: "144",
    name: "Sri Lanka",
    nameVi: "Sri Lanka",
    officialName: "Democratic Socialist Republic of Sri Lanka",
  },
  {
    alpha2: "LR",
    alpha3: "LBR",
    numeric: "430",
    name: "Liberia",
    nameVi: "Liberia",
    officialName: "Republic of Liberia",
  },
  {
    alpha2: "LS",
    alpha3: "LSO",
    numeric: "426",
    name: "Lesotho",
    nameVi: "Lesotho",
    officialName: "Kingdom of Lesotho",
  },
  {
    alpha2: "LT",
    alpha3: "LTU",
    numeric: "440",
    name: "Lithuania",
    nameVi: "Litva",
    officialName: "Republic of Lithuania",
  },
  {
    alpha2: "LU",
    alpha3: "LUX",
    numeric: "442",
    name: "Luxembourg",
    nameVi: "Luxembourg",
    officialName: "Grand Duchy of Luxembourg",
  },
  {
    alpha2: "LV",
    alpha3: "LVA",
    numeric: "428",
    name: "Latvia",
    nameVi: "Latvia",
    officialName: "Republic of Latvia",
  },
  {
    alpha2: "LY",
    alpha3: "LBY",
    numeric: "434",
    name: "Libya",
    nameVi: "Libya",
    officialName: "Libya",
  },
  {
    alpha2: "MA",
    alpha3: "MAR",
    numeric: "504",
    name: "Morocco",
    nameVi: "Ma-rốc",
    officialName: "Kingdom of Morocco",
  },
  {
    alpha2: "MC",
    alpha3: "MCO",
    numeric: "492",
    name: "Monaco",
    nameVi: "Monaco",
    officialName: "Principality of Monaco",
  },
  {
    alpha2: "MD",
    alpha3: "MDA",
    numeric: "498",
    name: "Moldova, Republic of",
    nameVi: "Moldova",
    officialName: "Republic of Moldova",
    commonName: "Moldova",
  },
  {
    alpha2: "ME",
    alpha3: "MNE",
    numeric: "499",
    name: "Montenegro",
    nameVi: "Montenegro",
    officialName: "Montenegro",
  },
  {
    alpha2: "MF",
    alpha3: "MAF",
    numeric: "663",
    name: "Saint Martin (French part)",
    nameVi: "St. Martin",
  },
  {
    alpha2: "MG",
    alpha3: "MDG",
    numeric: "450",
    name: "Madagascar",
    nameVi: "Madagascar",
    officialName: "Republic of Madagascar",
  },
  {
    alpha2: "MH",
    alpha3: "MHL",
    numeric: "584",
    name: "Marshall Islands",
    nameVi: "Quần đảo Marshall",
    officialName: "Republic of the Marshall Islands",
  },
  {
    alpha2: "MK",
    alpha3: "MKD",
    numeric: "807",
    name: "North Macedonia",
    nameVi: "Bắc Macedonia",
    officialName: "Republic of North Macedonia",
  },
  {
    alpha2: "ML",
    alpha3: "MLI",
    numeric: "466",
    name: "Mali",
    nameVi: "Mali",
    officialName: "Republic of Mali",
  },
  {
    alpha2: "MM",
    alpha3: "MMR",
    numeric: "104",
    name: "Myanmar",
    nameVi: "Myanmar (Miến Điện)",
    officialName: "Republic of Myanmar",
  },
  {
    alpha2: "MN",
    alpha3: "MNG",
    numeric: "496",
    name: "Mongolia",
    nameVi: "Mông Cổ",
  },
  {
    alpha2: "MO",
    alpha3: "MAC",
    numeric: "446",
    name: "Macao",
    nameVi: "Đặc khu Hành chính Macao, Trung Quốc",
    officialName: "Macao Special Administrative Region of China",
  },
  {
    alpha2: "MP",
    alpha3: "MNP",
    numeric: "580",
    name: "Northern Mariana Islands",
    nameVi: "Quần đảo Bắc Mariana",
    officialName: "Commonwealth of the Northern Mariana Islands",
  },
  {
    alpha2: "MQ",
    alpha3: "MTQ",
    numeric: "474",
    name: "Martinique",
    nameVi: "Martinique",
  },
  {
    alpha2: "MR",
    alpha3: "MRT",
    numeric: "478",
    name: "Mauritania",
    nameVi: "Mauritania",
    officialName: "Islamic Republic of Mauritania",
  },
  {
    alpha2: "MS",
    alpha3: "MSR",
    numeric: "500",
    name: "Montserrat",
    nameVi: "Montserrat",
  },
  {
    alpha2: "MT",
    alpha3: "MLT",
    numeric: "470",
    name: "Malta",
    nameVi: "Malta",
    officialName: "Republic of Malta",
  },
  {
    alpha2: "MU",
    alpha3: "MUS",
    numeric: "480",
    name: "Mauritius",
    nameVi: "Mauritius",
    officialName: "Republic of Mauritius",
  },
  {
    alpha2: "MV",
    alpha3: "MDV",
    numeric: "462",
    name: "Maldives",
    nameVi: "Maldives",
    officialName: "Republic of Maldives",
  },
  {
    alpha2: "MW",
    alpha3: "MWI",
    numeric: "454",
    name: "Malawi",
    nameVi: "Malawi",
    officialName: "Republic of Malawi",
  },
  {
    alpha2: "MX",
    alpha3: "MEX",
    numeric: "484",
    name: "Mexico",
    nameVi: "Mexico",
    officialName: "United Mexican States",
  },
  {
    alpha2: "MY",
    alpha3: "MYS",
    numeric: "458",
    name: "Malaysia",
    nameVi: "Malaysia",
  },
  {
    alpha2: "MZ",
    alpha3: "MOZ",
    numeric: "508",
    name: "Mozambique",
    nameVi: "Mozambique",
    officialName: "Republic of Mozambique",
  },
  {
    alpha2: "NA",
    alpha3: "NAM",
    numeric: "516",
    name: "Namibia",
    nameVi: "Namibia",
    officialName: "Republic of Namibia",
  },
  {
    alpha2: "NC",
    alpha3: "NCL",
    numeric: "540",
    name: "New Caledonia",
    nameVi: "New Caledonia",
  },
  {
    alpha2: "NE",
    alpha3: "NER",
    numeric: "562",
    name: "Niger",
    nameVi: "Niger",
    officialName: "Republic of the Niger",
  },
  {
    alpha2: "NF",
    alpha3: "NFK",
    numeric: "574",
    name: "Norfolk Island",
    nameVi: "Đảo Norfolk",
  },
  {
    alpha2: "NG",
    alpha3: "NGA",
    numeric: "566",
    name: "Nigeria",
    nameVi: "Nigeria",
    officialName: "Federal Republic of Nigeria",
  },
  {
    alpha2: "NI",
    alpha3: "NIC",
    numeric: "558",
    name: "Nicaragua",
    nameVi: "Nicaragua",
    officialName: "Republic of Nicaragua",
  },
  {
    alpha2: "NL",
    alpha3: "NLD",
    numeric: "528",
    name: "Netherlands",
    nameVi: "Hà Lan",
    officialName: "Kingdom of the Netherlands",
  },
  {
    alpha2: "NO",
    alpha3: "NOR",
    numeric: "578",
    name: "Norway",
    nameVi: "Na Uy",
    officialName: "Kingdom of Norway",
  },
  {
    alpha2: "NP",
    alpha3: "NPL",
    numeric: "524",
    name: "Nepal",
    nameVi: "Nepal",
    officialName: "Federal Democratic Republic of Nepal",
  },
  {
    alpha2: "NR",
    alpha3: "NRU",
    numeric: "520",
    name: "Nauru",
    nameVi: "Nauru",
    officialName: "Republic of Nauru",
  },
  {
    alpha2: "NU",
    alpha3: "NIU",
    numeric: "570",
    name: "Niue",
    nameVi: "Niue",
    officialName: "Niue",
  },
  {
    alpha2: "NZ",
    alpha3: "NZL",
    numeric: "554",
    name: "New Zealand",
    nameVi: "New Zealand",
  },
  {
    alpha2: "OM",
    alpha3: "OMN",
    numeric: "512",
    name: "Oman",
    nameVi: "Oman",
    officialName: "Sultanate of Oman",
  },
  {
    alpha2: "PA",
    alpha3: "PAN",
    numeric: "591",
    name: "Panama",
    nameVi: "Panama",
    officialName: "Republic of Panama",
  },
  {
    alpha2: "PE",
    alpha3: "PER",
    numeric: "604",
    name: "Peru",
    nameVi: "Peru",
    officialName: "Republic of Peru",
  },
  {
    alpha2: "PF",
    alpha3: "PYF",
    numeric: "258",
    name: "French Polynesia",
    nameVi: "Polynesia thuộc Pháp",
  },
  {
    alpha2: "PG",
    alpha3: "PNG",
    numeric: "598",
    name: "Papua New Guinea",
    nameVi: "Papua New Guinea",
    officialName: "Independent State of Papua New Guinea",
  },
  {
    alpha2: "PH",
    alpha3: "PHL",
    numeric: "608",
    name: "Philippines",
    nameVi: "Philippines",
    officialName: "Republic of the Philippines",
  },
  {
    alpha2: "PK",
    alpha3: "PAK",
    numeric: "586",
    name: "Pakistan",
    nameVi: "Pakistan",
    officialName: "Islamic Republic of Pakistan",
  },
  {
    alpha2: "PL",
    alpha3: "POL",
    numeric: "616",
    name: "Poland",
    nameVi: "Ba Lan",
    officialName: "Republic of Poland",
  },
  {
    alpha2: "PM",
    alpha3: "SPM",
    numeric: "666",
    name: "Saint Pierre and Miquelon",
    nameVi: "Saint Pierre và Miquelon",
  },
  {
    alpha2: "PN",
    alpha3: "PCN",
    numeric: "612",
    name: "Pitcairn",
    nameVi: "Quần đảo Pitcairn",
  },
  {
    alpha2: "PR",
    alpha3: "PRI",
    numeric: "630",
    name: "Puerto Rico",
    nameVi: "Puerto Rico",
  },
  {
    alpha2: "PS",
    alpha3: "PSE",
    numeric: "275",
    name: "Palestine, State of",
    nameVi: "Lãnh thổ Palestine",
    officialName: "the State of Palestine",
  },
  {
    alpha2: "PT",
    alpha3: "PRT",
    numeric: "620",
    name: "Portugal",
    nameVi: "Bồ Đào Nha",
    officialName: "Portuguese Republic",
  },
  {
    alpha2: "PW",
    alpha3: "PLW",
    numeric: "585",
    name: "Palau",
    nameVi: "Palau",
    officialName: "Republic of Palau",
  },
  {
    alpha2: "PY",
    alpha3: "PRY",
    numeric: "600",
    name: "Paraguay",
    nameVi: "Paraguay",
    officialName: "Republic of Paraguay",
  },
  {
    alpha2: "QA",
    alpha3: "QAT",
    numeric: "634",
    name: "Qatar",
    nameVi: "Qatar",
    officialName: "State of Qatar",
  },
  {
    alpha2: "RE",
    alpha3: "REU",
    numeric: "638",
    name: "Réunion",
    nameVi: "Réunion",
  },
  {
    alpha2: "RO",
    alpha3: "ROU",
    numeric: "642",
    name: "Romania",
    nameVi: "Romania",
  },
  {
    alpha2: "RS",
    alpha3: "SRB",
    numeric: "688",
    name: "Serbia",
    nameVi: "Serbia",
    officialName: "Republic of Serbia",
  },
  {
    alpha2: "RU",
    alpha3: "RUS",
    numeric: "643",
    name: "Russian Federation",
    nameVi: "Nga",
  },
  {
    alpha2: "RW",
    alpha3: "RWA",
    numeric: "646",
    name: "Rwanda",
    nameVi: "Rwanda",
    officialName: "Rwandese Republic",
  },
  {
    alpha2: "SA",
    alpha3: "SAU",
    numeric: "682",
    name: "Saudi Arabia",
    nameVi: "Ả Rập Xê-út",
    officialName: "Kingdom of Saudi Arabia",
  },
  {
    alpha2: "SB",
    alpha3: "SLB",
    numeric: "090",
    name: "Solomon Islands",
    nameVi: "Quần đảo Solomon",
  },
  {
    alpha2: "SC",
    alpha3: "SYC",
    numeric: "690",
    name: "Seychelles",
    nameVi: "Seychelles",
    officialName: "Republic of Seychelles",
  },
  {
    alpha2: "SD",
    alpha3: "SDN",
    numeric: "729",
    name: "Sudan",
    nameVi: "Sudan",
    officialName: "Republic of the Sudan",
  },
  {
    alpha2: "SE",
    alpha3: "SWE",
    numeric: "752",
    name: "Sweden",
    nameVi: "Thụy Điển",
    officialName: "Kingdom of Sweden",
  },
  {
    alpha2: "SG",
    alpha3: "SGP",
    numeric: "702",
    name: "Singapore",
    nameVi: "Singapore",
    officialName: "Republic of Singapore",
  },
  {
    alpha2: "SH",
    alpha3: "SHN",
    numeric: "654",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    nameVi: "St. Helena",
  },
  {
    alpha2: "SI",
    alpha3: "SVN",
    numeric: "705",
    name: "Slovenia",
    nameVi: "Slovenia",
    officialName: "Republic of Slovenia",
  },
  {
    alpha2: "SJ",
    alpha3: "SJM",
    numeric: "744",
    name: "Svalbard and Jan Mayen",
    nameVi: "Svalbard và Jan Mayen",
  },
  {
    alpha2: "SK",
    alpha3: "SVK",
    numeric: "703",
    name: "Slovakia",
    nameVi: "Slovakia",
    officialName: "Slovak Republic",
  },
  {
    alpha2: "SL",
    alpha3: "SLE",
    numeric: "694",
    name: "Sierra Leone",
    nameVi: "Sierra Leone",
    officialName: "Republic of Sierra Leone",
  },
  {
    alpha2: "SM",
    alpha3: "SMR",
    numeric: "674",
    name: "San Marino",
    nameVi: "San Marino",
    officialName: "Republic of San Marino",
  },
  {
    alpha2: "SN",
    alpha3: "SEN",
    numeric: "686",
    name: "Senegal",
    nameVi: "Senegal",
    officialName: "Republic of Senegal",
  },
  {
    alpha2: "SO",
    alpha3: "SOM",
    numeric: "706",
    name: "Somalia",
    nameVi: "Somalia",
    officialName: "Federal Republic of Somalia",
  },
  {
    alpha2: "SR",
    alpha3: "SUR",
    numeric: "740",
    name: "Suriname",
    nameVi: "Suriname",
    officialName: "Republic of Suriname",
  },
  {
    alpha2: "SS",
    alpha3: "SSD",
    numeric: "728",
    name: "South Sudan",
    nameVi: "Nam Sudan",
    officialName: "Republic of South Sudan",
  },
  {
    alpha2: "ST",
    alpha3: "STP",
    numeric: "678",
    name: "Sao Tome and Principe",
    nameVi: "São Tomé và Príncipe",
    officialName: "Democratic Republic of Sao Tome and Principe",
  },
  {
    alpha2: "SV",
    alpha3: "SLV",
    numeric: "222",
    name: "El Salvador",
    nameVi: "El Salvador",
    officialName: "Republic of El Salvador",
  },
  {
    alpha2: "SX",
    alpha3: "SXM",
    numeric: "534",
    name: "Sint Maarten (Dutch part)",
    nameVi: "Sint Maarten",
    officialName: "Sint Maarten (Dutch part)",
  },
  {
    alpha2: "SY",
    alpha3: "SYR",
    numeric: "760",
    name: "Syrian Arab Republic",
    nameVi: "Syria",
    commonName: "Syria",
  },
  {
    alpha2: "SZ",
    alpha3: "SWZ",
    numeric: "748",
    name: "Eswatini",
    nameVi: "Eswatini",
    officialName: "Kingdom of Eswatini",
  },
  {
    alpha2: "TC",
    alpha3: "TCA",
    numeric: "796",
    name: "Turks and Caicos Islands",
    nameVi: "Quần đảo Turks và Caicos",
  },
  {
    alpha2: "TD",
    alpha3: "TCD",
    numeric: "148",
    name: "Chad",
    nameVi: "Chad",
    officialName: "Republic of Chad",
  },
  {
    alpha2: "TF",
    alpha3: "ATF",
    numeric: "260",
    name: "French Southern Territories",
    nameVi: "Lãnh thổ phía Nam Thuộc Pháp",
  },
  {
    alpha2: "TG",
    alpha3: "TGO",
    numeric: "768",
    name: "Togo",
    nameVi: "Togo",
    officialName: "Togolese Republic",
  },
  {
    alpha2: "TH",
    alpha3: "THA",
    numeric: "764",
    name: "Thailand",
    nameVi: "Thái Lan",
    officialName: "Kingdom of Thailand",
  },
  {
    alpha2: "TJ",
    alpha3: "TJK",
    numeric: "762",
    name: "Tajikistan",
    nameVi: "Tajikistan",
    officialName: "Republic of Tajikistan",
  },
  {
    alpha2: "TK",
    alpha3: "TKL",
    numeric: "772",
    name: "Tokelau",
    nameVi: "Tokelau",
  },
  {
    alpha2: "TL",
    alpha3: "TLS",
    numeric: "626",
    name: "Timor-Leste",
    nameVi: "Timor-Leste",
    officialName: "Democratic Republic of Timor-Leste",
  },
  {
    alpha2: "TM",
    alpha3: "TKM",
    numeric: "795",
    name: "Turkmenistan",
    nameVi: "Turkmenistan",
  },
  {
    alpha2: "TN",
    alpha3: "TUN",
    numeric: "788",
    name: "Tunisia",
    nameVi: "Tunisia",
    officialName: "Republic of Tunisia",
  },
  {
    alpha2: "TO",
    alpha3: "TON",
    numeric: "776",
    name: "Tonga",
    nameVi: "Tonga",
    officialName: "Kingdom of Tonga",
  },
  {
    alpha2: "TR",
    alpha3: "TUR",
    numeric: "792",
    name: "Türkiye",
    nameVi: "Thổ Nhĩ Kỳ",
    officialName: "Republic of Türkiye",
  },
  {
    alpha2: "TT",
    alpha3: "TTO",
    numeric: "780",
    name: "Trinidad and Tobago",
    nameVi: "Trinidad và Tobago",
    officialName: "Republic of Trinidad and Tobago",
  },
  {
    alpha2: "TV",
    alpha3: "TUV",
    numeric: "798",
    name: "Tuvalu",
    nameVi: "Tuvalu",
  },
  {
    alpha2: "TW",
    alpha3: "TWN",
    numeric: "158",
    name: "Taiwan, Province of China",
    nameVi: "Đài Loan",
    officialName: "Taiwan, Province of China",
    commonName: "Taiwan",
  },
  {
    alpha2: "TZ",
    alpha3: "TZA",
    numeric: "834",
    name: "Tanzania, United Republic of",
    nameVi: "Tanzania",
    officialName: "United Republic of Tanzania",
    commonName: "Tanzania",
  },
  {
    alpha2: "UA",
    alpha3: "UKR",
    numeric: "804",
    name: "Ukraine",
    nameVi: "Ukraina",
  },
  {
    alpha2: "UG",
    alpha3: "UGA",
    numeric: "800",
    name: "Uganda",
    nameVi: "Uganda",
    officialName: "Republic of Uganda",
  },
  {
    alpha2: "UM",
    alpha3: "UMI",
    numeric: "581",
    name: "United States Minor Outlying Islands",
    nameVi: "Các tiểu đảo xa của Hoa Kỳ",
  },
  {
    alpha2: "US",
    alpha3: "USA",
    numeric: "840",
    name: "United States",
    nameVi: "Hoa Kỳ",
    officialName: "United States of America",
  },
  {
    alpha2: "UY",
    alpha3: "URY",
    numeric: "858",
    name: "Uruguay",
    nameVi: "Uruguay",
    officialName: "Eastern Republic of Uruguay",
  },
  {
    alpha2: "UZ",
    alpha3: "UZB",
    numeric: "860",
    name: "Uzbekistan",
    nameVi: "Uzbekistan",
    officialName: "Republic of Uzbekistan",
  },
  {
    alpha2: "VA",
    alpha3: "VAT",
    numeric: "336",
    name: "Holy See (Vatican City State)",
    nameVi: "Thành Vatican",
  },
  {
    alpha2: "VC",
    alpha3: "VCT",
    numeric: "670",
    name: "Saint Vincent and the Grenadines",
    nameVi: "St. Vincent và Grenadines",
  },
  {
    alpha2: "VE",
    alpha3: "VEN",
    numeric: "862",
    name: "Venezuela, Bolivarian Republic of",
    nameVi: "Venezuela",
    officialName: "Bolivarian Republic of Venezuela",
    commonName: "Venezuela",
  },
  {
    alpha2: "VG",
    alpha3: "VGB",
    numeric: "092",
    name: "Virgin Islands, British",
    nameVi: "Quần đảo Virgin thuộc Anh",
    officialName: "British Virgin Islands",
  },
  {
    alpha2: "VI",
    alpha3: "VIR",
    numeric: "850",
    name: "Virgin Islands, U.S.",
    nameVi: "Quần đảo Virgin thuộc Hoa Kỳ",
    officialName: "Virgin Islands of the United States",
  },
  {
    alpha2: "VN",
    alpha3: "VNM",
    numeric: "704",
    name: "Viet Nam",
    nameVi: "Việt Nam",
    officialName: "Socialist Republic of Viet Nam",
    commonName: "Vietnam",
  },
  {
    alpha2: "VU",
    alpha3: "VUT",
    numeric: "548",
    name: "Vanuatu",
    nameVi: "Vanuatu",
    officialName: "Republic of Vanuatu",
  },
  {
    alpha2: "WF",
    alpha3: "WLF",
    numeric: "876",
    name: "Wallis and Futuna",
    nameVi: "Wallis và Futuna",
  },
  {
    alpha2: "WS",
    alpha3: "WSM",
    numeric: "882",
    name: "Samoa",
    nameVi: "Samoa",
    officialName: "Independent State of Samoa",
  },
  {
    alpha2: "YE",
    alpha3: "YEM",
    numeric: "887",
    name: "Yemen",
    nameVi: "Yemen",
    officialName: "Republic of Yemen",
  },
  {
    alpha2: "YT",
    alpha3: "MYT",
    numeric: "175",
    name: "Mayotte",
    nameVi: "Mayotte",
  },
  {
    alpha2: "ZA",
    alpha3: "ZAF",
    numeric: "710",
    name: "South Africa",
    nameVi: "Nam Phi",
    officialName: "Republic of South Africa",
  },
  {
    alpha2: "ZM",
    alpha3: "ZMB",
    numeric: "894",
    name: "Zambia",
    nameVi: "Zambia",
    officialName: "Republic of Zambia",
  },
  {
    alpha2: "ZW",
    alpha3: "ZWE",
    numeric: "716",
    name: "Zimbabwe",
    nameVi: "Zimbabwe",
    officialName: "Republic of Zimbabwe",
  },
] as const satisfies readonly Country[];

export type CountryAlpha2 = (typeof COUNTRIES)[number]["alpha2"];
export type CountryAlpha3 = (typeof COUNTRIES)[number]["alpha3"];
export type CountryNumericCode = (typeof COUNTRIES)[number]["numeric"];

export const COUNTRY_BY_ALPHA2 = new Map<string, Country>(
  COUNTRIES.map((country) => [country.alpha2, country]),
);

export const COUNTRY_BY_ALPHA3 = new Map<string, Country>(
  COUNTRIES.map((country) => [country.alpha3, country]),
);

export const COUNTRY_BY_NUMERIC = new Map<string, Country>(
  COUNTRIES.map((country) => [country.numeric, country]),
);
