export const PASSPORT_DATE_CONFIG = {
  minYear: 1900,
  maxYear: 2099,
  twoDigitYearCutoff: 40,
  scanWindowLines: 3,
} as const

/** Common VIZ month names. Keys are uppercase and accent-free. */
export const PASSPORT_MONTH_ALIASES: Readonly<Record<string, number>> = {
  JAN: 1,
  JANUARY: 1,
  JANV: 1,
  ENE: 1,
  GEN: 1,
  FEB: 2,
  FEBRUARY: 2,
  FEV: 2,
  FEVR: 2,
  MAR: 3,
  MARCH: 3,
  MARS: 3,
  APR: 4,
  APRIL: 4,
  AVR: 4,
  ABR: 4,
  MAY: 5,
  MAI: 5,
  MAG: 5,
  JUN: 6,
  JUNE: 6,
  JUIN: 6,
  GIU: 6,
  JUL: 7,
  JULY: 7,
  JUIL: 7,
  LUG: 7,
  AUG: 8,
  AUGUST: 8,
  AOUT: 8,
  AGO: 8,
  SEP: 9,
  SEPT: 9,
  SEPTEMBER: 9,
  SET: 9,
  OCT: 10,
  OCTOBER: 10,
  OTT: 10,
  NOV: 11,
  NOVEMBER: 11,
  NOVE: 11,
  DEC: 12,
  DECEMBER: 12,
  DECE: 12,
  DIC: 12,
  DICEM: 12,
} as const
