import type { AppLocale } from '../types'

export const en = {
  common: { language: 'Language', chooseAnother: 'Choose another passport' },
  header: { localOnly: 'Local-only processing', sourceCode: 'Source code' },
  hero: { eyebrow: 'PRIVATE · FAST · ACCURATE', title: 'Scan passport.', accent: 'Skip the typing.', description: 'Read a passport photo page, verify its machine-readable data and auto-fill the form in your browser. Only passports are supported.' },
  workflow: { upload: 'Upload', extract: 'Extract', review: 'Review' },
  scanner: { title: 'Passport data page', hint: 'Upload the entire photo page, including the two rows of characters along the bottom edge.', imageTip: 'For better results, use a sharp, straight, evenly lit image with no glare, fingers or objects covering the page.', preparing: 'Preparing passport', preparingHint: 'Validating the image and initializing OCR…', errorTitle: 'Unable to scan passport' },
  upload: { aria: 'Upload passport data page image', drop: 'Drop a passport image here', title: 'Upload passport image', description: 'Click anywhere in this area or drag and drop an image', choose: 'Choose image', formats: 'JPG, PNG or WEBP · max 12 MB', rejected: 'The passport image must be JPG, PNG or WEBP and no larger than 12 MB.', privacy: 'Your passport image is processed only in this browser and never leaves your device.' },
  preview: { alt: 'Passport data page preview', change: 'Choose another image', changeAria: 'Choose another passport image', processing: 'Scanning passport…', scan: 'Scan passport', scanAgain: 'Scan passport again' },
  form: { eyebrow: 'Auto-filled data', title: 'Passport details', description: 'Compare every field with the original passport and edit it before confirming.', autoFilled: 'Filled from passport', reviewHint: 'OCR can be inaccurate when the image is blurred or reflective. Verify all values against the original passport.', emptyHint: 'Upload a passport data page and select “Scan passport” to auto-fill the form.', confirmed: 'Confirmed', saving: 'Saving…', submit: 'Confirm passport details' },
  fields: { passportNumber: 'Passport number', surname: 'Last name', givenName: 'First and middle name', fullName: 'Full name', nationality: 'Nationality', gender: 'Gender', dateOfBirth: 'Date of birth', issueDate: 'Date of issue', expiryDate: 'Date of expiry' },
  select: { nationalityPlaceholder: 'Select nationality', searchNationality: 'Search by country or code', noNationality: 'No matching country', genderPlaceholder: 'Select gender', male: 'Male (M)', female: 'Female (F)', unspecified: 'Unspecified (X)' },
  errors: { INVALID_FILE: 'The passport image is invalid. Use JPG, PNG or WEBP up to 12 MB.', IMAGE_UNREADABLE: 'The passport image could not be opened. Choose an undamaged, sharp image with sufficient resolution.', NOT_PASSPORT: 'This image is not a passport data page. Only passports are supported.', MRZ_NOT_FOUND: 'The two rows of characters at the bottom of the passport could not be read. Include the full page and keep this area sharp and unobstructed.', OCR_INITIALIZATION_FAILED: 'The passport scanner could not start. Check your network connection and try again.', OCR_TIMEOUT: 'The passport scan timed out. Try a sharper, smaller image or retake the data page.', OCR_FAILED: 'Passport details could not be recognized. Use a sharp, glare-free image that includes the entire data page.' },
  formErrors: { invalidDate: 'Invalid date', nonexistentDate: 'Date does not exist', passportMin: 'Use at least 6 characters', passportMax: 'Use at most 12 characters', alphanumeric: 'Use letters and numbers only', surnameRequired: 'Surname is required', givenNameRequired: 'Given name is required', fullNameRequired: 'Full name is required', nationalityLength: 'Choose a nationality', nationalityInvalid: 'Choose a valid ICAO nationality', genderRequired: 'Choose M, F or X', birthPast: 'Date of birth must be in the past', expired: 'This passport has expired', issueAfterBirth: 'Issue date must be after date of birth', expiryAfterIssue: 'Expiry date must be after issue date' },
  footer: { author: 'Author: Tien Thu' },
} as const satisfies AppLocale
